### ISSUE TITLE
Missing configuration for Text Formats

### ISSUE THREAD

**Issue by gocaps** [ubc-web-services/ubc_d8_config_modules#3]
- Add Allowed HTML tags, so selected buttons appear
`<p class="text-*"> <u> <sub> <sup>`

 - Select CKEditor in Text editor select box

**Comment by occupant** [comment]
The first issue has been corrected in https://github.com/ubc-web-services/ubc_d8_config_modules/commit/6cd67b316f0cf9c4b7db7aade654a9f7ae653b96

For the second, was this using the develop branch or mater? All current code is in develop - I've been waiting to update master until I had a solid release ready.
